import React, {
  StyleSheet,
} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  titleBar: {
    marginTop: 10,
    marginBottom: 10,
  },
  title: {
    fontFamily: 'AvenirNextLTPro-Bold',
    fontSize: 22,
    lineHeight: 22,
    color: '#000000',
    textAlign: 'center',
  },
  publishButtonView: {
    position: 'absolute',
    right: 0,
    marginRight: 20,
  },
  publishButton: {
    fontFamily: 'AvenirNextLTPro-Regular',
    fontSize: 20,
    lineHeight: 20,
    color: '#565656',
    textAlign: 'center',
  },
  backImgView: {
    position: 'absolute',
    left: 20,
    width: 35,
    height: 35,
    // justifyContent: 'center',
  },
  backImgButton:{
    width: 20,
    height: 20,
    resizeMode: 'contain',
  },
  mainView: {
    backgroundColor: '#f5f5f5',
  },
  contentView: {
    margin: '5%',
  },
  addPhotoVideoView: {
    borderStyle: 'dashed',
    borderColor: '#86939c',
    borderRadius: 20,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addPhotoVideoImage: {
    marginTop: 10,
    width: '100%',
    height: 60,
    resizeMode: 'contain',
  },
  addPhotoVideoText: {
    fontFamily: 'AvenirNextLTPro-Regular',
    fontSize: 15,
    lineHeight: 15,
    color: '#86939c',
    textAlign: 'center',
    marginBottom: 10,
    marginTop: 10,
  },
  groupNameView: {
    marginTop: 20,
    borderRadius: 20,
    backgroundColor: '#fff',
    alignItems: 'center',
    flexDirection: 'row',
  },
  groupNameAvatarView: {
    margin: 20,
  },
  groupNameText: {
    fontFamily: 'AvenirNextLTPro-Bold',
    fontSize: 17,
    lineHeight: 17,
    color: '#000',
    textAlign: 'center',
    marginTop: 5,
  },
  addressView :{
    marginTop: 20,
    borderRadius: 20,
    backgroundColor: '#fff',
    alignItems: 'center',
    flexDirection: 'row',
  },
  addressImage: {
    width: 20,
    height: 20,
    margin: 20,
    resizeMode: 'contain',
  },
  addressText: {
    fontFamily: 'AvenirNextLTPro-Regular',
    fontSize: 16,
    lineHeight: 16,
    color: '#000',
    textAlign: 'center',
    marginLeft: 10,
    marginTop: 5,
  },
  addressExpandImage: {
    width: 20,
    height: 20,
    margin: 20,
    resizeMode: 'contain',
    position: 'absolute',
    right: 0,
  },
  videoGroupTitle: {
    marginTop: 20,
    fontFamily: 'AvenirNextLTPro-Bold',
    fontSize: 17,
    lineHeight: 17,
    color: '#000',
  },
  videoGroupText: {
    marginTop: 10,
    fontFamily: 'AvenirNextLTPro-Regular',
    fontSize: 12,
    lineHeight: 12,
    color: '#86939c',
  },
  addVideoView: {
    marginTop: 20,
    borderStyle: 'dashed',
    borderColor: '#86939c',
    borderRadius: 20,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addVideoImage: {
    marginTop: 10,
    width: '100%',
    height: 60,
    resizeMode: 'contain',
  },
  addVideoText: {
    fontFamily: 'AvenirNextLTPro-Regular',
    fontSize: 15,
    lineHeight: 15,
    color: '#86939c',
    textAlign: 'center',
    marginBottom: 10,
    marginTop: 10,
  },
  videoLongView: {
    marginTop: 20,
    alignItems: 'center',
    flexDirection: 'row',
  },
  videoLongText: {
    fontFamily: 'AvenirNextLTPro-Regular',
    fontSize: 15,
    lineHeight: 15,
    color: '#000',
    textAlign: 'center',
    marginBottom: 10,
    marginTop: 10,
  },
  videoLongButton: {
    backgroundColor: '#ff5b8c',
    borderRadius: 15,
    position: 'absolute',
    right: 0,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoLongButtonText: {
    fontFamily: 'AvenirNextLTPro-Regular',
    fontSize: 12,
    lineHeight: 12,
    color: '#fff',
    textAlign: 'center',
    marginLeft: 15,
    marginRight: 15,
    marginTop: 4,
  },
  descriptionView :{
    marginTop: 20,
    borderRadius: 20,
    backgroundColor: '#fff',
    alignItems: 'center',
    flexDirection: 'row',
  },
  descriptionImage: {
    width: 20,
    height: 20,
    margin: 20,
    resizeMode: 'contain',
  },
  descriptionText: {
    fontFamily: 'AvenirNextLTPro-Regular',
    fontSize: 16,
    lineHeight: 16,
    color: '#000',
    textAlign: 'center',
    marginTop: 5,
  },
  typeActivityView :{
    marginTop: 20,
    borderRadius: 20,
    backgroundColor: '#fff',
    alignItems: 'center',
    flexDirection: 'row',
  },
  typeActivityImage: {
    width: 20,
    height: 20,
    margin: 20,
    resizeMode: 'contain',
  },
  typeActivityText: {
    fontFamily: 'AvenirNextLTPro-Regular',
    fontSize: 16,
    lineHeight: 16,
    color: '#000',
    textAlign: 'center',
    marginTop: 5,
  },
  typeActivityExpandImage: {
    width: 20,
    height: 20,
    margin: 20,
    resizeMode: 'contain',
    position: 'absolute',
    right: 0,
  },
  numberView :{
    marginTop: 20,
    borderRadius: 20,
    backgroundColor: '#fff',
  },
  numberTopView: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  numberImage: {
    width: 20,
    height: 20,
    margin: 20,
    resizeMode: 'contain',
  },
  numberText: {
    fontFamily: 'AvenirNextLTPro-Regular',
    fontSize: 16,
    lineHeight: 16,
    color: '#000',
    textAlign: 'center',
    marginLeft: 10,
    marginTop: 5,
  },
  numberValue: {
    fontFamily: 'AvenirNextLTPro-Bold',
    fontSize: 16,
    lineHeight: 16,
    color: '#00ccd2',
    textAlign: 'center',
    position: 'absolute',
    right: 0,
    marginRight: 20,
  },
  numberSliderView: {
    marginLeft: 20,
    marginRight: 20,
    marginTop: 10,
    marginBottom: 10,
  },
  slider: {
    height: 30,
    borderRadius: 10,
  },
  dateView :{
    marginTop: 20,
    borderRadius: 20,
    backgroundColor: '#fff',
    marginBottom: 20,
  },
  startDateView :{
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 10,
    marginBottom: 10,
  },
  startDateImage: {
    width: 20,
    height: 20,
    margin: 20,
    resizeMode: 'contain',
  },
  startDateTextView: {

  },
  dateLabelText: {
    fontFamily: 'AvenirNextLTPro-Regular',
    fontSize: 16,
    lineHeight: 16,
    color: '#86939c',
  },
  dateValueText: {
    fontFamily: 'AvenirNextLTPro-Regular',
    fontSize: 16,
    lineHeight: 16,
    color: '#000',
    textAlign: 'center',
    marginTop: 5,
  },
  dateExpandImage: {
    width: 20,
    height: 20,
    margin: 20,
    resizeMode: 'contain',
    position: 'absolute',
    right: 0,
  },
  buttonTextRed: {
    fontFamily: 'AvenirNextLTPro-Regular',
    fontSize: 15,
    lineHeight: 15,
    color: '#ff5b8c',
    textAlign: 'center',
    marginTop: 10,
    marginLeft: 15,
    marginRight: 35,
    marginBottom: 10,
  },

  buttonTextWhite: {
    fontFamily: 'AvenirNextLTPro-Regular',
    fontSize: 15,
    lineHeight: 15,
    color: '#ffffff',
    textAlign: 'center',
    marginTop: 10,
    marginLeft: 15,
    marginRight: 35,
    marginBottom: 5,
  },
});